### ISSUE TITLE
Documentation for core algorithms

### ISSUE THREAD

**Issue by nagq** [rcombs/Cube.js#2]
I am a beginner of Rubik's cube. I'm interested in the cube algorithm, and I want to implement the Two-Phase algorithm by myslef.

But I don't know much about algorithms. Could you please provide documentation for beginners.

**Comment by rcombs** [comment]
You'll want to read up on the details at Kociemba's site: http://kociemba.org/cube.htm

**Comment by nagq** [comment]
thanks
